version: "3.8"

services:
  pg:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./server/.env
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - myApp

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - /user/src/app/node_modules
      - ./server:/usr/src/app
    depends_on:
      - pg
    ports:
      - "5000:5000"
    networks:
      - myApp

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - /user/src/app/node_modules
      - ./frontend:/usr/src/app
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - myApp

volumes:
  pg:
    driver: local

networks:
  myApp:
    driver: bridge

